### ISSUE TITLE
footer appears in the wrong place

### ISSUE THREAD

**Issue by simonfossom** [huridocs/uwazi#2821]
This happened few times but I can't reproduce it. I don't know what do to with it so I'm documenting it here.

![Screenshot_2020-03-13 Settings • Commission on Human Rights (Republic of the Philippines)](https://user-images.githubusercontent.com/8134850/76850084-ed82e780-6846-11ea-89f1-bd0eb10beb62.png)

**Comment by txau** [comment]
Footer HTML and CSS seems to be messy in this section. First of all, remove the footer containing the Uwazi logo. This footer is not present in any other section in settings and it is part of the problem.

Then remove the background: white, from the settings-footer class.

**Comment by txau** [comment]
This was introduced along with the CSS for the topic classification adaptation of the thesauri. I fixed it for regular thesauri section, I didn't have the time to check the topic classification one but I tried to fix this in a non-intrusive way.

**Comment by nwyu** [comment]
This was fixed for several weeks, but the same problem has reappeared again.

![Thesauri footer](https://user-images.githubusercontent.com/56067374/81019628-58c06180-8e67-11ea-8a7d-8755e39b1c1c.png)

**Comment by txau** [comment]
I'll take a look.

**Comment by txau** [comment]
@nwyu can you let me know which browser/version you are using. Also, can you double check if it is still happening?

**Comment by nwyu** [comment]
@txau It is still happening on the Thesauri page. It looks normal at first, but when you scroll to view more, the button moves up (which also blocks the ability to edit the two lists below it). Same problem on both Firefox 76.0.1 and Chrome 83.0.4103.61.
